version: '2'
services:
  db:
    image: mysql
    container_name: Yii2-mysql
    ports:
      - 6604:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "testuser1"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./mysql/data/:/var/lib/mysql
    restart: always

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: phongnx_php-fpm
    restart: always
    volumes:
      - ./www/:/var/www/html
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/php-fpm:/var/log/php-fpm
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: phongnx_nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx
    volumes_from:
      - php
    ports:
      - 80:80

  memcached:
    image: memcached
    container_name: phongnx_memcached
    ports:
      - "11211:11211"

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phongnx_phpmyadmin
    restart: always
    ports:
      - "8000:80"
